#!/usr/bin/env ruby
# frozen_string_literal: true

# Two rules, both enforced here rather than trusted to habit: no em-dashes, and
# no tool attribution anywhere in the tracked tree.
BANNED = {
  "em-dash" => /—/,
  "en-dash in prose" => /–/,
  "tool attribution" => /\b(claude|copilot|chatgpt|codex|cursor\.sh)\b/i,
  "generated-by claim" => /generated by ai|ai-assisted|written by ai|co-authored-by: *(claude|copilot)/i
}.freeze

SKIP = %r{\A(LICENSE|Gemfile\.lock|coverage/|tmp/|script/check_prose\.rb)}

failures = []

`git ls-files`.each_line(chomp: true).each do |file|
  next if file.match?(SKIP)
  next unless File.file?(file)
  next if File.binread(file, 8000).to_s.include?("\x00")

  File.readlines(file, encoding: "UTF-8").each_with_index do |line, index|
    BANNED.each do |label, pattern|
      failures << "#{file}:#{index + 1}: #{label}: #{line.strip}" if line.match?(pattern)
    end
  end
end

if failures.empty?
  puts "prose ok"
  exit 0
end

warn failures.join("\n")
warn "\n#{failures.length} prose violation(s)"
exit 1
