#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "leakproof"

# The detector table is generated from the registry, so documentation and
# behaviour cannot drift apart. Run with --check in CI.
STRENGTH = {
  "CRC32 checksum" => "proof",
  "ASN.1 key parse" => "proof",
  "decode and expiry" => "proof",
  "account ID extraction" => "structure",
  "prefix and length only" => "weak",
  "none" => "none"
}.freeze

def table(registry)
  rows = registry.sort_by(&:id).map do |detector|
    kind = detector.secret? ? "credential" : "public by design"
    strength = STRENGTH.fetch(detector.validity.describes, "weak")
    "| `#{detector.id}` | #{detector.name} | #{detector.validity.describes} | #{strength} | #{kind} |"
  end
  <<~TEXT
    <!-- Generated by script/generate_docs.rb. Do not edit by hand. -->

    # Detectors

    Every registered rule, with the offline check it actually gets. The weak rows
    are here on purpose: a rule that can only compare a prefix and a length says
    so, rather than borrowing the credibility of the rules that carry a proof.

    Only a rule in the `proof` column can put a finding in the confirmed tier.
    See [confidence.md](confidence.md) for why.

    | rule | name | offline check | strength | kind |
    |---|---|---|---|---|
    #{rows.join("\n")}

    ## Notes

    #{registry.sort_by(&:id).filter_map { |d| "- `#{d.id}`: #{d.notes}" if d.notes }.join("\n")}
  TEXT
end

registry = Leakproof::Detectors::Registry.default
target = File.expand_path("../docs/detectors.md", __dir__)
generated = table(registry)

if ARGV.include?("--check")
  current = File.exist?(target) ? File.read(target) : ""
  if current == generated
    puts "docs/detectors.md is current"
    exit 0
  end
  warn "docs/detectors.md is stale. Run: ruby script/generate_docs.rb"
  exit 1
end

File.write(target, generated)
puts "wrote docs/detectors.md (#{registry.size} rules)"
